module.exports.crew = `**Crew Creation.**
1. Choose a crew type.
2. Choose an initial repuation and lair.
3. Establish your hunting grounds.
4. Choose a special ability.
5. Assign crew upgrades.
6. Choose a favourite contact.`;

module.exports.crew1 = `**1. Choose a crew type**
The crew type determines the group’s purpose, their special abilities, and how they advance. You begin at Tier 0, with strong hold and 0 rep. You start with 2 coin.`;

module.exports.crew2 = `**2. Choose an initial repuation and lair.**
Choose how other underworld factions see you: Ambitious, Brutal,  Daring, Honorable, Professional,  Savvy, Subtle, Strange.

Look at the map and pick a district in which to place your lair. Describe the lair.
`;
module.exports.crew3 = `**3. Establish your hunting grounds.**
Look at the map and pick a district in which to place your hunting grounds. Decide how to deal with the faction that claims that area.

- Pay them 1 coin.
- Pay them 2 coin. Get +1 status.
- Pay nothing. Get -1 status.`;

module.exports.crew4 = `**4. Choose a special ability.**
They’re in the gray column in the middle of the crew sheet. If you can’t decide, choose the first ability on the list. It’s placed there as a good first option.`;

module.exports.crew5 = `**5. Assign crew upgrades.**
Your crew has two upgrades pre-selected. Choose two more. If your crew has a cohort, follow the procedure to create it. Record the faction status changes due to your upgrades:

One faction helped you get an upgrade. Take +1 status with them. Or spend 1 coin for +2 status instead.

One faction was harmed when you got an upgrade. Take -2 status with them. Or spend 1 coin for -1 status instead.`;

module.exports.crew6 = `**6. Choose a favourite contact.**
Mark the one who is a close friend, long-time ally, or partner in crime. Record the faction status changes related to your contact:

One faction is friendly with your contact. Take +1 status with them.

One faction is unfriendly with your contact. Take -1 status with them.

At your option, increase the intensity of the factions’ relationship with your contact and take +2 and -2 status, instead.`;

module.exports.advance = `**Crew Advancement**
When you fill your crew advancement tracker, clear the marks and take a new special ability or mark two crew upgrade boxes.

Every time the crew advances, each PC gets stash equal to the crew Tier + 2, to represent profits generated by the crew as they’ve been operating.`;

module.exports.tier = `**Tier**
Your Tier determines the quality level of your items as well as the quality and scale of the gangs your crew employs—and thereby what size of enemy you can expect to handle.

**Hold**
On the faction ladder next to the Tier numbers is a letter indicating the strength of each faction’s hold. Hold represents how well a faction can maintain their current position on the ladder. W indicates weak hold. S indicates strong hold. Being at War will decrease your hold, and potentially your tier.

**Development & Rep**
When you accrue enough rep, the other factions take you more seriously and you attract the support needed to develop and grow. You need 12 rep to fill the rep tracker, less any turf you have. When you fill the tracker, do one of the following:

- If your hold is weak: It becomes strong. Reset your rep to zero.
- If your hold is strong: You can pay to increase your crew Tier by one. This costs coin equal to your new Tier x 8. Once you pay and increase your Tier, reset your rep to zero and reduce your hold to weak.

As long as your rep tracker is full, you don’t earn new rep`;

module.exports.upgrade = `**Crew Upgrades**
**Boat house** You have a boat, a dock on a waterway, and a small shack to store boating supplies. A second upgrade improves the boat with armor and more cargo capacity.

**Quarters** Your lair includes living quarters for the crew. Without this upgrade, each PC sleeps elsewhere, and is vulnerable when they do so.

**Secure Lair** Your lair has locks, alarms, and traps to thwart intruders. A second upgrade improves the defenses to include arcane measures that work against spirits.

**Carriage House** You have a carriage, two goats to pull it, and a stable. A second upgrade improves the carriage with armor and larger, swifter goats.

**Cohort** A cohort is a gang or a single expert NPC who works for your crew.

**Training** If you have a Training upgrade, you earn 2 xp (instead of 1) when you train a given xp track during downtime. See \` $train \`.

**Hidden Lair** Your lair has a secret location and is disguised to hide it from view. If your lair is discovered, use two downtime activities and pay coin equal to your Tier to relocate and hide once again.

**Mastery** You may advance your PCs’ action ratings to 4 (actions are usually capped at 3). This costs four upgrade boxes to unlock. 

**Vault** Your lair has a secure vault, increasing your storage capacity for coin to 8. A second upgrade increases your capacity to 16. A separate part of your vault can be used as a holding cell.

**Quality** Each upgrade improves the quality rating of all the PCs’ items of that type, beyond the quality established by the crew’s Tier and fine items. You can improve the quality of Documents, Gear (covers Burglary Gear and Climbing Gear), Arcane Implements, Subterfuge Supplies, Tools (covers Demolitions Tools and Tinkering Tools), and Weapons.

**Workshop** Your lair has a workshop appointed with tools for tinkering and alchemy, a small library of books, documents, and maps. You may accomplish long-term projects without leaving your lair.`;
