module.exports.advance = `**Crew Advancement**
When you fill your crew advancement tracker, clear the marks and take a new special ability or mark two crew upgrade boxes.

Every time the crew advances, each PC gets stash equal to the crew Tier + 2, to represent profits generated by the crew as they’ve been operating.`;

module.exports.tier = `**Tier**
Your Tier determines the quality level of your items as well as the quality and scale of the gangs your crew employs—and thereby what size of enemy you can expect to handle.

**Hold**
On the faction ladder next to the Tier numbers is a letter indicating the strength of each faction’s hold. Hold represents how well a faction can maintain their current position on the ladder. W indicates weak hold. S indicates strong hold. Being at War will decrease your hold, and potentially your tier.

**Development & Rep**
When you accrue enough rep, the other factions take you more seriously and you attract the support needed to develop and grow. You need 12 rep to fill the rep tracker, less any turf you have. When you fill the tracker, do one of the following:

- If your hold is weak: It becomes strong. Reset your rep to zero.
- If your hold is strong: You can pay to increase your crew Tier by one. This costs coin equal to your new Tier x 8. Once you pay and increase your Tier, reset your rep to zero and reduce your hold to weak.

As long as your rep tracker is full, you don’t earn new rep`;

module.exports.upgrade = `**Crew Upgrades**
**Boat house** You have a boat, a dock on a waterway, and a small shack to store boating supplies. A second upgrade improves the boat with armor and more cargo capacity.

**Quarters** Your lair includes living quarters for the crew. Without this upgrade, each PC sleeps elsewhere, and is vulnerable when they do so.

**Secure Lair** Your lair has locks, alarms, and traps to thwart intruders. A second upgrade improves the defenses to include arcane measures that work against spirits.

**Carriage House** You have a carriage, two goats to pull it, and a stable. A second upgrade improves the carriage with armor and larger, swifter goats.

**Cohort** A cohort is a gang or a single expert NPC who works for your crew.

**Training** If you have a Training upgrade, you earn 2 xp (instead of 1) when you train a given xp track during downtime. See \` $train \`.

**Hidden Lair** Your lair has a secret location and is disguised to hide it from view. If your lair is discovered, use two downtime activities and pay coin equal to your Tier to relocate and hide once again.

**Mastery** You may advance your PCs’ action ratings to 4 (actions are usually capped at 3). This costs four upgrade boxes to unlock. 

**Vault** Your lair has a secure vault, increasing your storage capacity for coin to 8. A second upgrade increases your capacity to 16. A separate part of your vault can be used as a holding cell.

**Quality** Each upgrade improves the quality rating of all the PCs’ items of that type, beyond the quality established by the crew’s Tier and fine items. You can improve the quality of Documents, Gear (covers Burglary Gear and Climbing Gear), Arcane Implements, Subterfuge Supplies, Tools (covers Demolitions Tools and Tinkering Tools), and Weapons.

**Workshop** Your lair has a workshop appointed with tools for tinkering and alchemy, a small library of books, documents, and maps. You may accomplish long-term projects without leaving your lair.`;
